[package]
name = "pliantdb-client"
version = "0.1.0-dev-1"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "Client for accessing PliantDB servers."
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations"]
readme = "../README.md"

[dependencies]
pliantdb-networking = { path = "../networking", version = "0.1.0-dev-1" }
