[package]
name = "pliantdb-client"
version = "0.1.0-dev-1"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "Client for accessing PliantDB servers."
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations"]
readme = "../README.md"

[dependencies]
pliantdb-core = { path = "../core", version = "0.1.0-dev-1", features = ["networking"] }
thiserror = "1"
url = "2.2"
flume = "0.10"
tokio = { version = "1" }
futures = "0.3"
async-trait = "0.1"
once_cell = "1"
serde_cbor = "0.11"

[dev-dependencies]
pliantdb-server = { path = "../server", version = "0.1.0-dev-1", features = ["test-util", "certificate"] }
anyhow = "1"
