[workspace]

members = [
    "circulate",
    "client",
    "core",
    "jobs",
    "local",
    "macros",
    "pliantdb",
    "server",
]

[patch.crates-io]
# fabruic = { path = "../fabruic", version = "0.0.1-dev.2" }
actionable = { git = "https://github.com/khonsulabs/actionable.git", branch = "main", version = "0.1.0-dev.2" }
