[package]
name = "pliantdb"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1"
anyhow = "1"
sled = "0.34"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
sha2 = "0.9"

[dev-dependencies]
hex-literal = "0.3"
