[workspace]

members = [
    "circulate",
    "client",
    "core",
    "jobs",
    "local",
    "macros",
    "bonsaidb",
    "server",
    "roots",
    "xtask",
]

[patch.crates-io]
# fabruic = { path = "../fabruic", version = "0.0.1-dev.2" }
# actionable = { git="https://github.com/khonsulabs/actionable.git", branch="main" }
# actionable = { path="../actionable/actionable", version="0.1.0-dev.4" }

# [patch."https://github.com/khonsulabs/custodian.git"]
# custodian-password = { path="../custodian/password", branch="main" }
[profile.bench]
# debug = true # for flamegraph
lto = true
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
