[package]
name = "pliantdb-core"
version = "0.1.0-dev-0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "Core functionality and types for PliantDB."
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations", "database"]
readme = "../README.md"

[features]
default = []
test-util = []

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
async-trait = "0.1"
uuid = { version = "0.8", features = ["v4", "serde"] }
thiserror = "1"
anyhow = "1"
sha2 = "0.9"

[dev-dependencies]
hex-literal = "0.3"
