[package]
name = "pliantdb-server"
version = "0.1.0-dev-1"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "Database server for PliantDB."
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations"]
readme = "../README.md"

[dependencies]
pliantdb-protocol = { path = "../protocol", version = "0.1.0-dev-1" }
pliantdb-local = { path = "../local", version = "0.1.0-dev-1" }
