[package]
name = "pliantdb-server"
version = "0.1.0-dev-1"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "Database server for PliantDB."
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations"]
readme = "../README.md"

[features]
default = []
cli = ["pliantdb-networking/certificate", "structopt", "anyhow"]
test-util = ["pliantdb-core/test-util", "anyhow"]

[dependencies]
pliantdb-networking = { path = "../networking", version = "0.1.0-dev-1", features = ["certificate"] }
pliantdb-core = { path = "../core", version = "0.1.0-dev-1" }
pliantdb-local = { path = "../local", version = "0.1.0-dev-1" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "1"
async-trait = "0.1"
structopt = { version = "0.3", optional = true }
anyhow = { version = "1", optional = true }
futures = "0.3"
flume = "0.10"
itertools = "0.10"

[dev-dependencies]
anyhow = "1"
pliantdb-core = { path = "../core", version = "0.1.0-dev-1", features = ["test-util"] }
