[package]
name = "pliantdb"
version = "0.1.0-dev-0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "a programmable document database inspired by CouchDB"
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations", "database"]
readme = "../README.md"

[[example]]
name = "basic-local"
required-features = ["local"]

[features]
default = ["full"]
full = ["local"]
local = ["pliantdb-local"]

[dependencies]
pliantdb-core = { path = "../core", version = "0.1.0-dev-0" }
pliantdb-local = { path = "../local", version = "0.1.0-dev-0", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
