[package]
name = "pliantdb"
version = "0.1.0-dev-1"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "a programmable document database inspired by CouchDB"
repository = "https://github.com/khonsulabs/pliantdb"
license = "MIT OR Apache-2.0"
keywords = ["document-database", "database"]
categories = ["database-implementations", "database"]
readme = "../README.md"

[[bin]]
name = "pliantdb"
path = "src/main.rs"
required-features = ["cli"]

[[example]]
name = "basic-local"
required-features = ["local"]

[features]
default = ["cli"]
full = ["local"]
local = ["pliantdb-local"]
cli = ["full", "anyhow", "tokio", "structopt", "pliantdb-local/cli"]

[dependencies]
pliantdb-core = { path = "../core", version = "0.1.0-dev-1" }
pliantdb-local = { path = "../local", version = "0.1.0-dev-1", optional = true }

tokio = { version = "1", features = ["full"], optional = true }
structopt = { version = "0.3", optional = true }
anyhow = { version = "1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
