[book]
authors = ["Jonathan Johnson"]
language = "en"
multilingual = false
src = "src"
title = "PliantDb User's Guide"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
follow-web-links = false
