name: Tests

on: [push]

jobs:
  xtask-test-matrix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Generate matrix
        id: xtask
        run: |
          cargo xtask test-matrix

    outputs:
      matrix: ${{ steps.xtask.outputs.test-matrix }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: xtask-test-matrix
    strategy:
      fail-fast: false
      matrix:
        options: ${{ fromJson(needs.xtask-test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run clippy
        run: |
          cd ${{ matrix.options.folder }}
          cargo clippy ${{ matrix.options.cargo_args }} -- -D warnings 

      - name: Run unit tests
        run: |
          cd ${{ matrix.options.folder }}
          cargo test ${{ matrix.options.cargo_args }} -- --nocapture
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_ACCESS_KEY_SECRET: ${{ secrets.S3_ACCESS_KEY_SECRET }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

  check-wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Install wasm32-unknown-unknown
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Run clippy
        run: |
          cargo clippy --target wasm32-unknown-unknown --package bonsaidb-client -- -D warnings
